///make_dialog(name,depart,dialog,is_solo,spr1,spr2,left_spr_black,speed)
instance_create_v(x,y,obj_dialogbox,
                        argument0,
                        argument1,
                        argument2,
                        argument3,
                        argument4,
                        argument5,
                        argument6,
                        argument7)
